apiVersion: networking.k8s.io/v1  # 인그레스 객체의 API 버전
kind: Ingress # 생성할 객체의 유형
metadata:
  name: polar-ingress # 인그레스 이름
spec:
  ingressClassName: nginx # 이 객체를 관리할 인그레스 컨트롤러 설정
  rules:
    - http: # HTTP 트래픽에 대한 인그레스 규칙
        paths:
          - path: / # 모든 요청에 대한 기본 설정 규칙
            pathType: Prefix
            backend:
              service:
                name: edge-service  # 트래픽을 전달할 서비스 객체의 이름
                port:
                  number: 80  # 트래픽을 전달할 서비스의 포트 번호